version: "3.8"

services:
  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver_lab5
    restart: unless-stopped
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__WEBSERVER__SECRET_KEY: "lab5_secret_key"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../:/opt/airflow/repo
      - ./airflow_home/airflow.db:/opt/airflow/airflow.db
      - mlflow_data:/mlflow_data
    ports:
      - "8081:8080"
      - "5000:5000"
    command: bash -c "pip install --user dvc mlflow pandas scikit-learn matplotlib pyyaml optuna hydra-core joblib pyarrow && airflow db init && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler_lab5
    restart: unless-stopped
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__WEBSERVER__SECRET_KEY: "lab5_secret_key"
    volumes:
      - ./dags:/opt/airflow/dags
      - ../:/opt/airflow/repo
      - ./airflow_home/airflow.db:/opt/airflow/airflow.db
      - mlflow_data:/mlflow_data
    command: bash -c "pip install --user dvc mlflow pandas scikit-learn matplotlib pyyaml optuna hydra-core joblib pyarrow && airflow scheduler"

volumes:
  mlflow_data: