version: "3.8"

services:
  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver_lab5
    restart: unless-stopped
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    ports:
      - "8081:8080"
    command: bash -c "pip install dvc mlflow pandas scikit-learn matplotlib pyyaml optuna hydra-core && airflow db init && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler_lab5
    restart: unless-stopped
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    command: bash -c "pip install dvc mlflow pandas scikit-learn matplotlib pyyaml optuna hydra-core && airflow scheduler"